### ISSUE TITLE
Crashing Homebridge on default new install

### ISSUE THREAD

**Issue by jamie-2bit** [troygNZ/homebridge-solax#35]
Default install on the latest docker image I get this as soon as I restart Homebridge:

[1/6/2022, 11:37:58 AM] TypeError: Cannot read properties of undefined (reading 'join')
    at Function.logDetails (/homebridge/node_modules/homebridge-solax/src/config.ts:25:72)
    at new SolaxPlatform (/homebridge/node_modules/homebridge-solax/src/solaxPlatform.ts:24:18)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[1/6/2022, 11:37:58 AM] Got SIGTERM, shutting down Homebridge...

**Comment by troygNZ** [comment]
Thanks. What docker image are you using? I'm using Onzu, but haven't updated for a little while. I'll try and reproduce and report back.
Cheers
Troy

**Comment by troygNZ** [comment]
I've managed to reproduce it on the latest version of Onzu docker image, but also on an earlier verison. This error is due to no alerts thresholds being specified. I'll update the code to handle this gracefully, though ideally should always have at-least 1 alert threshold defined.

In the interim, if you specify a value for at-least one item, it'll work.

**Comment by jamie-2bit** [comment]
Perfect! Thanks.

**Comment by troygNZ** [comment]
Version 1.3.3 will now handle no alert thresholds being specified. Cheers.
